### ISSUE TITLE
Data import crashes

### ISSUE THREAD

**Issue by teunvink** [NLNOG/irrexplorer#135]
The data importer (`poetry run import-data`) seems to crash sometimes:
```
Sat 22 Jan 2022 12:41:15 AM UTC
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/irrexplorer2/irrexplorer/scripts.py", line 33, in import_data
    asyncio.run(import_data_command.main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/irrexplorer2/irrexplorer/irrexplorer/commands/import_data.py", line 17, in main
    await asyncio.gather(*tasks)
  File "/home/irrexplorer2/irrexplorer/irrexplorer/backends/rirstats.py", line 27, in run_import
    text = await retrieve_url_text(url)
  File "/home/irrexplorer2/irrexplorer/irrexplorer/backends/common.py", line 55, in retrieve_url_text
    return await response.text()
  File "/home/irrexplorer2/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1076, in text
    await self.read()
  File "/home/irrexplorer2/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1032, in read
    self._body = await self.content.read()
  File "/home/irrexplorer2/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 370, in read
    block = await self.readany()
  File "/home/irrexplorer2/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 392, in readany
    await self._wait("readany")
  File "/home/irrexplorer2/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 306, in _wait
    await waiter
  File "/home/irrexplorer2/venv/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Command exited with non-zero status 1
254.93user 19.10system 5:02.19elapsed 90%CPU (0avgtext+0avgdata 562292maxresident)k
3808inputs+0outputs (13major+258455minor)pagefaults 0swaps
```

It is unclear what causes this crash (a guess would be a connection to one of the RIRs). A better explanation what happened, with which connection and what the preferred action by the user would be is useful.

**Comment by mxsasha** [comment]
Likely related to incidental network issues, I can add a graceful catch and log line.

**Comment by teunvink** [comment]
I don't think we've seen any more of these issues in the last couple of months.

**Comment by teunvink** [comment]
Still haven't seen any of these issues, I'm closing this on.
