### ISSUE TITLE
IRR explorer backend crashes

### ISSUE THREAD

**Issue by teunvink** [NLNOG/irrexplorer#194]
The import process crashed:
```
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>                                                                                                                                                                       [14/1875]
Traceback (most recent call last):
  File "asyncpg/protocol/coreproto.pyx", line 122, in asyncpg.protocol.protocol.CoreProtocol._read_server_messages
  File "asyncpg/protocol/coreproto.pyx", line 708, in asyncpg.protocol.protocol.CoreProtocol._push_result
  File "asyncpg/protocol/protocol.pyx", line 890, in asyncpg.protocol.protocol.BaseProtocol._on_result
  File "asyncpg/protocol/protocol.pyx", line 812, in asyncpg.protocol.protocol.BaseProtocol._dispatch_result
AttributeError: 'NoneType' object has no attribute 'cancelled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 546, in data_received
    self._app_protocol.data_received(chunk)
  File "asyncpg/protocol/protocol.pyx", line 938, in asyncpg.protocol.protocol.BaseProtocol.data_received
  File "asyncpg/protocol/coreproto.pyx", line 143, in asyncpg.protocol.protocol.CoreProtocol._read_server_messages
  File "asyncpg/protocol/coreproto.pyx", line 708, in asyncpg.protocol.protocol.CoreProtocol._push_result
  File "asyncpg/protocol/protocol.pyx", line 890, in asyncpg.protocol.protocol.BaseProtocol._on_result
  File "asyncpg/protocol/protocol.pyx", line 812, in asyncpg.protocol.protocol.BaseProtocol._dispatch_result
AttributeError: 'NoneType' object has no attribute 'cancelled'
Traceback (most recent call last):
  File "asyncpg/protocol/coreproto.pyx", line 122, in asyncpg.protocol.protocol.CoreProtocol._read_server_messages
  File "asyncpg/protocol/coreproto.pyx", line 708, in asyncpg.protocol.protocol.CoreProtocol._push_result
  File "asyncpg/protocol/protocol.pyx", line 890, in asyncpg.protocol.protocol.BaseProtocol._on_result
  File "asyncpg/protocol/protocol.pyx", line 812, in asyncpg.protocol.protocol.BaseProtocol._dispatch_result
AttributeError: 'NoneType' object has no attribute 'cancelled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/irrexplorer2/irrexplorer/scripts.py", line 33, in import_data
    asyncio.run(import_data_command.main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/irrexplorer2/irrexplorer/irrexplorer/commands/import_data.py", line 17, in main
    await asyncio.gather(*tasks)
  File "/home/irrexplorer2/irrexplorer/irrexplorer/backends/bgp.py", line 31, in run_import
    await self._load_prefixes(prefixes)
  File "/home/irrexplorer2/irrexplorer/irrexplorer/backends/bgp.py", line 80, in _load_prefixes
    raise ImporterError(f"Failed to insert BGP data: {de}")
  File "/home/irrexplorer2/venv/lib/python3.8/site-packages/databases/core.py", line 335, in __aexit__
    await self.rollback()
  File "/home/irrexplorer2/venv/lib/python3.8/site-packages/databases/core.py", line 382, in rollback
    await self._connection.__aexit__()
  File "/home/irrexplorer2/venv/lib/python3.8/site-packages/databases/core.py", line 232, in __aexit__
    await self._connection.release()
  File "/home/irrexplorer2/venv/lib/python3.8/site-packages/databases/backends/postgres.py", line 147, in release
    self._connection = await self._database._pool.release(self._connection)
  File "/home/irrexplorer2/venv/lib/python3.8/site-packages/asyncpg/pool.py", line 833, in release
    return await asyncio.shield(ch.release(timeout))
  File "/home/irrexplorer2/venv/lib/python3.8/site-packages/asyncpg/pool.py", line 185, in release
    await self._con.close(timeout=timeout)
  File "/home/irrexplorer2/venv/lib/python3.8/site-packages/asyncpg/connection.py", line 1314, in close
    await self._protocol.close(timeout)
  File "asyncpg/protocol/protocol.pyx", line 604, in close
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 546, in data_received
    self._app_protocol.data_received(chunk)
  File "asyncpg/protocol/protocol.pyx", line 938, in asyncpg.protocol.protocol.BaseProtocol.data_received
  File "asyncpg/protocol/coreproto.pyx", line 143, in asyncpg.protocol.protocol.CoreProtocol._read_server_messages
  File "asyncpg/protocol/coreproto.pyx", line 708, in asyncpg.protocol.protocol.CoreProtocol._push_result
  File "asyncpg/protocol/protocol.pyx", line 890, in asyncpg.protocol.protocol.BaseProtocol._on_result
  File "asyncpg/protocol/protocol.pyx", line 812, in asyncpg.protocol.protocol.BaseProtocol._dispatch_result
AttributeError: 'NoneType' object has no attribute 'cancelled'
Command exited with non-zero status 1
395.26user 26.25system 7:49.94elapsed 89%CPU (0avgtext+0avgdata 592672maxresident)k
888inputs+0outputs (8major+332944minor)pagefaults 0swaps
```

**Comment by teunvink** [comment]
Closing this issue, since it was caused by disk being full, not a 'regular' crash which we've been experiencing more often.
